[package]
name = "bidi-text"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-bidi = "0.3"
unicode-segmentation = "1.11"
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "std",
] }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.4"
