[package]
name = "bidi-text"
version = "0.1.0"
edition = "2024"

[dependencies]
unicode-bidi = "0.3"
unicode-segmentation = "1.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
proptest = "1.4"
