[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
pdfium-render = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1.35", features = ["full"] }

[dev-dependencies]
tempfile = "3.8"
