[package]
name = "ui-components"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.1"
editor-core = { path = "../editor-core" }
bidi-text = { path = "../bidi-text" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
