[package]
name = "editor-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ropey = "1.6"
unicode-segmentation = "1.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
proptest = "1.4"
